ktor:
    application:
        modules:
            - com.ktor.ApplicationKt.module
    deployment:
        port: 8089

    database:
        driver: "org.mariadb.jdbc.Driver"
        url: "jdbc:mariadb://localhost:3307/appRecetas"
        username: "admin"
        password: "admin"